[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y tesseract-ocr poppler-utils"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.12" 
