[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.10"
PORT = "8000"
PYTHONUNBUFFERED = "1" 
