[build]
builder = "nixpacks"
buildCommand = """
apt-get update && \
apt-get install -y \
    tesseract-ocr \
    poppler-utils \
    python3-dev \
    python3-distutils \
    python3-setuptools \
    build-essential \
    libpoppler-cpp-dev \
    pkg-config \
    python3-pip \
    libmagic1 \
    && pip install --upgrade pip setuptools wheel
"""

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.10"
PORT = "8000"
PYTHONUNBUFFERED = "1" 
